const fs = require("fs");
const path = require("path");

const agentCategories = [
  {
    id: "engineering", name: "Engineering", emoji: "", color: "tag-cyan",
    description: "Full-stack engineering agents for building, deploying, and maintaining software systems.",
    source: "agency",
    agents: [
      { id: "frontend-developer", name: "Frontend Developer", emoji: "", specialty: "UI/UX Engineering", description: "Builds responsive, accessible, and performant user interfaces using modern frameworks.", whenToUse: "Use when you need to create or improve web UI components, layouts, or frontend architecture." },
      { id: "backend-architect", name: "Backend Architect", emoji: "", specialty: "Server & API Design", description: "Designs scalable backend systems, APIs, and microservices architectures.", whenToUse: "Use when designing server-side systems, REST/GraphQL APIs, or distributed architectures." },
      { id: "mobile-app-builder", name: "Mobile App Builder", emoji: "", specialty: "iOS & Android Development", description: "Develops cross-platform mobile applications using React Native or Flutter.", whenToUse: "Use when building or maintaining iOS, Android, or cross-platform mobile apps." },
      { id: "ai-engineer", name: "AI Engineer", emoji: "", specialty: "ML & AI Integration", description: "Integrates machine learning models and AI capabilities into production applications.", whenToUse: "Use when adding AI features, fine-tuning models, or building ML pipelines." },
      { id: "devops-automator", name: "DevOps Automator", emoji: "", specialty: "CI/CD & Infrastructure", description: "Automates deployment pipelines, infrastructure provisioning, and operational workflows.", whenToUse: "Use when setting up CI/CD, containerization, or cloud infrastructure automation." },
      { id: "rapid-prototyper", name: "Rapid Prototyper", emoji: "", specialty: "Fast MVP Development", description: "Quickly builds functional prototypes and MVPs to validate ideas and gather feedback.", whenToUse: "Use when you need a working prototype fast to test a concept or demo to stakeholders." },
      { id: "senior-developer", name: "Senior Developer", emoji: "", specialty: "Full-Stack Expertise", description: "Provides senior-level guidance on architecture decisions, code quality, and best practices.", whenToUse: "Use for complex technical decisions, code reviews, or mentoring on best practices." },
      { id: "security-engineer", name: "Security Engineer", emoji: "", specialty: "Application Security", description: "Identifies vulnerabilities, implements security controls, and ensures secure coding practices.", whenToUse: "Use when auditing code for security issues, implementing auth, or hardening systems." },
      { id: "embedded-firmware-engineer", name: "Embedded Firmware Engineer", emoji: "", specialty: "Embedded Systems", description: "Develops firmware and low-level software for embedded systems and IoT devices.", whenToUse: "Use when working with microcontrollers, RTOS, or hardware-level programming." },
      { id: "incident-response-commander", name: "Incident Response Commander", emoji: "", specialty: "Incident Management", description: "Coordinates rapid response to production incidents, outages, and critical system failures.", whenToUse: "Use during production incidents to coordinate response, triage, and resolution." },
      { id: "solidity-engineer", name: "Solidity Smart Contract Engineer", emoji: "", specialty: "Blockchain Development", description: "Writes, audits, and deploys smart contracts on Ethereum and EVM-compatible chains.", whenToUse: "Use when building DeFi protocols, NFT contracts, or any on-chain business logic." },
      { id: "codebase-onboarding-engineer", name: "Codebase Onboarding Engineer", emoji: "", specialty: "Code Navigation", description: "Helps developers quickly understand large codebases through guided exploration and documentation.", whenToUse: "Use when joining a new project or onboarding team members to an existing codebase." },
      { id: "technical-writer", name: "Technical Writer", emoji: "", specialty: "Documentation", description: "Creates clear, comprehensive technical documentation, API references, and developer guides.", whenToUse: "Use when writing docs, READMEs, API references, or developer onboarding materials." },
      { id: "code-reviewer", name: "Code Reviewer", emoji: "", specialty: "Code Quality", description: "Performs thorough code reviews focusing on correctness, performance, and maintainability.", whenToUse: "Use when you need a detailed review of a PR or want to improve code quality." },
      { id: "database-optimizer", name: "Database Optimizer", emoji: "", specialty: "Database Performance", description: "Optimizes database schemas, queries, and indexing strategies for maximum performance.", whenToUse: "Use when dealing with slow queries, schema design, or database scaling challenges." },
      { id: "git-workflow-master", name: "Git Workflow Master", emoji: "", specialty: "Version Control", description: "Designs and enforces Git branching strategies, commit conventions, and merge workflows.", whenToUse: "Use when setting up Git workflows, resolving conflicts, or improving team VCS practices." },
      { id: "software-architect", name: "Software Architect", emoji: "", specialty: "System Architecture", description: "Designs high-level software architectures that balance scalability, maintainability, and performance.", whenToUse: "Use when making major architectural decisions or designing new systems from scratch." },
      { id: "sre", name: "SRE", emoji: "", specialty: "Site Reliability", description: "Ensures system reliability through SLOs, error budgets, monitoring, and chaos engineering.", whenToUse: "Use when improving system reliability, setting up monitoring, or defining SLAs." },
      { id: "data-engineer", name: "Data Engineer", emoji: "", specialty: "Data Pipelines", description: "Builds and maintains data pipelines, ETL processes, and data warehouse architectures.", whenToUse: "Use when building data ingestion, transformation, or analytics infrastructure." },
      { id: "cms-developer", name: "CMS Developer", emoji: "", specialty: "Content Management", description: "Implements and customizes content management systems for editorial and marketing teams.", whenToUse: "Use when building or customizing CMS platforms like WordPress, Contentful, or Sanity." }
    ]
  },
  {
    id: "design", name: "Design", emoji: "", color: "tag-pink",
    description: "Creative design agents for UI, UX, branding, and visual storytelling.",
    source: "agency",
    agents: [
      { id: "ui-designer", name: "UI Designer", emoji: "", specialty: "Interface Design", description: "Creates beautiful, pixel-perfect user interfaces with strong visual hierarchy and design systems.", whenToUse: "Use when designing screens, components, or establishing a visual design language." },
      { id: "ux-researcher", name: "UX Researcher", emoji: "", specialty: "User Research", description: "Conducts user research, usability testing, and synthesizes insights to inform product decisions.", whenToUse: "Use when you need user insights, usability testing plans, or research synthesis." },
      { id: "ux-architect", name: "UX Architect", emoji: "", specialty: "Information Architecture", description: "Structures information architecture, user flows, and navigation systems for intuitive experiences.", whenToUse: "Use when designing site maps, user flows, or complex navigation structures." },
      { id: "brand-guardian", name: "Brand Guardian", emoji: "", specialty: "Brand Identity", description: "Maintains brand consistency across all touchpoints and enforces design system standards.", whenToUse: "Use when reviewing brand compliance, creating brand guidelines, or auditing visual consistency." },
      { id: "visual-storyteller", name: "Visual Storyteller", emoji: "", specialty: "Visual Narrative", description: "Crafts compelling visual narratives through illustration, motion, and multimedia design.", whenToUse: "Use when creating presentations, explainer visuals, or narrative-driven design content." },
      { id: "whimsy-injector", name: "Whimsy Injector", emoji: "", specialty: "Delightful Interactions", description: "Adds playful micro-interactions, animations, and delightful details that make products memorable.", whenToUse: "Use when you want to add personality, fun animations, or memorable micro-interactions." },
      { id: "image-prompt-engineer", name: "Image Prompt Engineer", emoji: "", specialty: "AI Image Generation", description: "Crafts precise prompts for AI image generation tools to produce stunning, on-brand visuals.", whenToUse: "Use when generating AI images for marketing, UI mockups, or creative projects." },
      { id: "inclusive-visuals-specialist", name: "Inclusive Visuals Specialist", emoji: "", specialty: "Accessible Design", description: "Ensures visual designs meet accessibility standards and are inclusive for all users.", whenToUse: "Use when auditing designs for accessibility, color contrast, or inclusive representation." }
    ]
  },
  {
    id: "marketing", name: "Marketing", emoji: "", color: "tag-orange",
    description: "Growth and content marketing agents for every channel and audience.",
    source: "agency",
    agents: [
      { id: "growth-hacker", name: "Growth Hacker", emoji: "", specialty: "Growth Strategy", description: "Identifies and executes rapid growth experiments across acquisition, activation, and retention.", whenToUse: "Use when you need growth strategies, funnel optimization, or viral loop design." },
      { id: "content-creator", name: "Content Creator", emoji: "", specialty: "Content Strategy", description: "Produces engaging, SEO-optimized content across blogs, social media, and email campaigns.", whenToUse: "Use when creating blog posts, social content, newsletters, or content calendars." },
      { id: "seo-specialist", name: "SEO Specialist", emoji: "", specialty: "Search Optimization", description: "Optimizes content and technical SEO to improve organic search rankings and traffic.", whenToUse: "Use when improving search rankings, conducting keyword research, or technical SEO audits." },
      { id: "tiktok-strategist", name: "TikTok Strategist", emoji: "", specialty: "Short-Form Video", description: "Creates viral TikTok content strategies leveraging trends, sounds, and platform algorithms.", whenToUse: "Use when building a TikTok presence or creating short-form video content strategies." },
      { id: "instagram-curator", name: "Instagram Curator", emoji: "", specialty: "Visual Social Media", description: "Curates aesthetically cohesive Instagram feeds with strategic content and engagement tactics.", whenToUse: "Use when managing Instagram presence, planning visual content, or growing followers." },
      { id: "linkedin-content-creator", name: "LinkedIn Content Creator", emoji: "", specialty: "B2B Social Content", description: "Creates thought leadership content and professional narratives that drive B2B engagement.", whenToUse: "Use when building professional brand presence or creating B2B content on LinkedIn." },
      { id: "reddit-community-builder", name: "Reddit Community Builder", emoji: "", specialty: "Community Marketing", description: "Builds authentic Reddit presence through community engagement and value-driven content.", whenToUse: "Use when engaging Reddit communities, managing subreddits, or community-led growth." },
      { id: "social-media-strategist", name: "Social Media Strategist", emoji: "", specialty: "Multi-Platform Strategy", description: "Develops cohesive social media strategies across all platforms to build brand awareness.", whenToUse: "Use when creating a unified social media strategy or managing multi-platform presence." },
      { id: "ai-citation-strategist", name: "AI Citation Strategist", emoji: "", specialty: "AI Search Optimization", description: "Optimizes content to be cited by AI assistants and appear in AI-generated answers.", whenToUse: "Use when optimizing for AI search engines, ChatGPT citations, or Perplexity visibility." },
      { id: "video-optimization-specialist", name: "Video Optimization Specialist", emoji: "", specialty: "Video SEO", description: "Optimizes video content for YouTube, search, and social platforms to maximize reach.", whenToUse: "Use when optimizing YouTube videos, video SEO, or cross-platform video distribution." },
      { id: "podcast-strategist", name: "Podcast Strategist", emoji: "", specialty: "Podcast Growth", description: "Develops podcast content strategies, episode planning, and audience growth tactics.", whenToUse: "Use when launching or growing a podcast, planning episodes, or improving discoverability." },
      { id: "app-store-optimizer", name: "App Store Optimizer", emoji: "", specialty: "ASO", description: "Optimizes app store listings to improve visibility, conversion rates, and downloads.", whenToUse: "Use when improving App Store or Google Play listings, screenshots, or keyword rankings." }
    ]
  },
